# Developed by Metrum AI for Dell

# Prometheus scrape configuration file
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: metrics
    static_configs:
    - targets:
      - prometheus:9090
      - node_exporter:9100
      - ipmi_exporter:9290
      - e_smi_tool:10112
  - job_name: vllm
    scrape_interval: 2s
    static_configs:
      - targets:
        - vllm_serving_0:8000
        - vllm_serving_1:8000
